2022-05-31 23:07:44 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-31 23:07:44 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'hacs' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2022-05-31 23:07:44 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xboxone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-31 23:07:44 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'xboxone' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2022-05-31 23:08:01 ERROR (SyncWorker_2) [homeassistant.components.quantum_gateway.device_tracker] Unable to login to gateway. Check password and host
2022-05-31 23:08:02 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy quantum_gateway
2022-05-31 23:08:07 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2022-05-31 23:26:42 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '397', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 03:26:42 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-05-31 23:28:24 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '397', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 03:28:24 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-05-31 23:30:44 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '373', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 03:30:44 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-05-31 23:35:57 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '373', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 03:35:57 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:37:49 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '532', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:37:49 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:38:09 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '532', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:38:09 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:40:40 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:40 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:40 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:40 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:40 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '435', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:40:40 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:40:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:40:52 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '435', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:40:52 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:41:01 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.name}} is 10% or below
{% endfor %}'
2022-06-01 00:41:01 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.name}} is 10% or below
{% endfor %}'
2022-06-01 00:41:01 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.name}} is 10% or below
{% endfor %}'
2022-06-01 00:41:01 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'str object' has no attribute 'name' when rendering '{% for inkLevel in [states('sensor.ink_level_black'), states('sensor.ink_level_cyan'), states('sensor.ink_level_magenta'), states('sensor.ink_level_yellow')] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.name}} is 10% or below
{% endfor %}'
2022-06-01 00:41:01 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '435', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:41:01 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:42:12 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '445', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:42:12 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:44:13 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'sensor' is undefined when rendering '{% for inkLevel in [sensor.ink_level_black, sensor.ink_level_cyan, sensor.ink_level_magenta, sensor.ink_level_yellow] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:44:13 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'sensor' is undefined
2022-06-01 00:44:13 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547718087296] Error handling message: Error rendering data template: UndefinedError: 'sensor' is undefined (unknown_error)
2022-06-01 00:44:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'homeassistant.helpers.template.TemplateState object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states.sensor.ink_level_black, states.sensor.ink_level_cyan, states.sensor.ink_level_magenta, states.sensor.ink_level_yellow] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:44:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'homeassistant.helpers.template.TemplateState object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states.sensor.ink_level_black, states.sensor.ink_level_cyan, states.sensor.ink_level_magenta, states.sensor.ink_level_yellow] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:44:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'homeassistant.helpers.template.TemplateState object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states.sensor.ink_level_black, states.sensor.ink_level_cyan, states.sensor.ink_level_magenta, states.sensor.ink_level_yellow] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:44:51 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'homeassistant.helpers.template.TemplateState object' has no attribute 'friendly_name' when rendering '{% for inkLevel in [states.sensor.ink_level_black, states.sensor.ink_level_cyan, states.sensor.ink_level_magenta, states.sensor.ink_level_yellow] %}
  {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%} {{inkLevel.friendly_name}} is 10% or below
{% endfor %}'
2022-06-01 00:44:51 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '435', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:44:51 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:45:15 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '1097', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:45:15 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 00:46:32 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Error sending notification to https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3: ContentTypeError(RequestInfo(url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3'), method='POST', headers=<CIMultiDictProxy('Host': 'us-central1-ha-client-c73c4.cloudfunctions.net', 'User-Agent': 'HomeAssistant/2022.5.5 aiohttp/3.8.1 Python/3.9', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '1097', 'Content-Type': 'application/json')>, real_url=URL('https://us-central1-ha-client-c73c4.cloudfunctions.net/pushNotifyV3')), (), message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', headers=<CIMultiDictProxy('Content-Length': '272', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Wed, 01 Jun 2022 04:46:32 GMT', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"')>)
2022-06-01 02:29:19 WARNING (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-01 02:29:35 ERROR (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.28', 8009)), retrying in 5.0s
2022-06-01 04:10:18 ERROR (Thread-9) [pychromecast.socket_client] [(192.168.1.38):32104] Error reading from socket.
2022-06-01 04:10:18 WARNING (Thread-9) [pychromecast.socket_client] [(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-01 04:10:18 ERROR (Thread-9) [pychromecast.socket_client] [(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-01 04:10:46 WARNING (Thread-8) [pychromecast.socket_client] [(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-01 04:11:01 ERROR (Thread-8) [pychromecast.socket_client] [(192.168.1.38):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 8009)), retrying in 5.0s
2022-06-01 04:11:04 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-01 04:11:04 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-01 04:11:04 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-01 04:18:34 ERROR (MainThread) [homeassistant.components.steam_online] Error fetching steam_online data: Server took too long to respond
2022-06-01 04:27:00 WARNING (Thread-7) [pychromecast.socket_client] [(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-01 04:27:16 ERROR (Thread-7) [pychromecast.socket_client] [(192.168.1.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 8009)), retrying in 5.0s
2022-06-01 05:33:10 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-01 08:16:09 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.front_bedroom_fan_1, light.lifx_mini_3a3c40
2022-06-01 10:46:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-01 19:00:17 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-01 20:24:05 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-02 01:24:08 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.front_bedroom_fan_1, light.lifx_mini_3a3c40
2022-06-02 02:16:24 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error reading from socket.
2022-06-02 02:16:24 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-02 02:16:24 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-02 02:16:54 WARNING (Thread-8) [pychromecast.socket_client] [(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-02 02:17:01 ERROR (Thread-8) [pychromecast.socket_client] [(192.168.1.38):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 8009)), retrying in 5.0s
2022-06-02 02:17:09 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-02 02:17:09 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-02 02:17:09 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-02 04:04:30 WARNING (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-02 04:04:46 ERROR (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.28', 8009)), retrying in 5.0s
2022-06-02 04:15:16 WARNING (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-02 04:15:31 ERROR (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 8009)), retrying in 5.0s
2022-06-02 05:32:46 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-02 05:46:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-02 13:27:36 WARNING (zeroconf-ServiceBrowser-_googlecast._tcp-226) [pychromecast.dial] Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='VizioCastDisplay0396._googlecast._tcp.local.')})
2022-06-02 13:27:43 ERROR (Thread-16) [pychromecast.socket_client] [VizioCastDisplay0396(192.168.1.172):8009] Error reading from socket.
2022-06-02 13:27:43 WARNING (Thread-16) [pychromecast.socket_client] [VizioCastDisplay0396(192.168.1.172):8009] Error communicating with socket, resetting connection
2022-06-02 15:22:16 WARNING (Thread-16) [pychromecast.socket_client] [VizioCastDisplay0396(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-02 15:22:23 ERROR (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Failed to connect to service ServiceInfo(type='mdns', data='Living Room Vizio._googlecast._tcp.local.'), retrying in 5.0s
2022-06-02 16:03:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-02 17:58:05 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-02 20:24:47 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-03 02:22:26 WARNING (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-03 02:42:46 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error reading from socket.
2022-06-03 02:42:46 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-03 02:42:46 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-03 02:43:15 WARNING (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-03 02:43:31 ERROR (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 8009)), retrying in 5.0s
2022-06-03 02:43:32 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-03 02:43:32 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-03 02:43:32 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-03 02:51:10 WARNING (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-03 02:51:12 WARNING (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-03 02:51:13 WARNING (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-03 02:51:13 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Heartbeat timeout, resetting connection
2022-06-03 02:51:14 WARNING (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-03 03:43:16 WARNING (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-03 03:43:31 ERROR (Thread-6) [pychromecast.socket_client] [(192.168.1.28):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.28', 8009)), retrying in 5.0s
2022-06-03 03:51:16 WARNING (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-03 03:51:32 ERROR (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 8009)), retrying in 5.0s
2022-06-03 05:32:41 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-03 07:17:10 ERROR (MainThread) [homeassistant.components.steam_online] Error fetching steam_online data: Server took too long to respond
2022-06-03 13:08:22 WARNING (MainThread) [homeassistant.components.lifx.light] Duplicate LIFX discovery response ignored
2022-06-03 13:08:22 WARNING (MainThread) [homeassistant.components.lifx.light] Duplicate LIFX discovery response ignored
2022-06-03 17:29:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-03 17:54:45 WARNING (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-03 17:54:52 ERROR (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Failed to connect to service ServiceInfo(type='mdns', data='Living Room Vizio._googlecast._tcp.local.'), retrying in 5.0s
2022-06-03 18:53:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-03 20:11:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
2022-06-03 20:25:43 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-04 01:34:11 WARNING (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-04 01:34:18 ERROR (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Failed to connect to service ServiceInfo(type='mdns', data='Living Room Vizio._googlecast._tcp.local.'), retrying in 5.0s
2022-06-04 03:16:08 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error reading from socket.
2022-06-04 03:16:08 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-04 03:16:08 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-04 03:16:38 WARNING (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-04 03:16:45 ERROR (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 8009)), retrying in 5.0s
2022-06-04 03:16:54 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-04 03:16:54 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-04 03:16:54 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-04 03:20:18 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error reading from socket.
2022-06-04 03:20:18 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-04 03:20:18 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-04 03:39:39 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-04 03:39:39 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-04 03:39:40 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-04 03:40:10 WARNING (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-04 03:40:17 ERROR (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 8009)), retrying in 5.0s
2022-06-04 04:25:26 WARNING (Thread-6) [pychromecast.socket_client] [Master Bedroom TV(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-04 04:25:33 ERROR (Thread-6) [pychromecast.socket_client] [Master Bedroom TV(192.168.1.28):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.28', 8009)), retrying in 5.0s
2022-06-04 05:32:04 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-04 06:24:26 WARNING (Thread-3) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2022-06-04 06:24:26 WARNING (Thread-3) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.1.13, code UNKNOWN_ERROR
2022-06-04 06:24:26 WARNING (Thread-3) [roombapy.remote_client] Unknown disconnection error: ID=16.Kindly use https://github.com/pschmitt/roombapy/issues/new
2022-06-04 06:24:26 WARNING (Thread-3) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.1.13, code UNKNOWN_ERROR
2022-06-04 12:15:43 WARNING (MainThread) [homeassistant.components.duckdns] Updating DuckDNS domain failed: opsmart
2022-06-04 12:40:10 WARNING (MainThread) [homeassistant.components.http.security_filter] Filtered a potential harmful request to: /vpn/../vpns/cfg/smb.conf
2022-06-04 14:18:41 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 14:18:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 14:18:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 14:18:44 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 14:18:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 14:18:46 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-06-04 20:26:08 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-04 23:50:10 ERROR (MainThread) [aioharmony.hubconnector_websocket] 192.168.1.8: Connection timed out for hub 17519306
2022-06-05 02:23:12 WARNING (Thread-6) [pychromecast.socket_client] [Master Bedroom TV(192.168.1.28):8009] Heartbeat timeout, resetting connection
2022-06-05 02:23:19 ERROR (Thread-6) [pychromecast.socket_client] [Master Bedroom TV(192.168.1.28):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.28', 8009)), retrying in 5.0s
2022-06-05 03:35:02 WARNING (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Heartbeat timeout, resetting connection
2022-06-05 03:35:10 ERROR (Thread-7) [pychromecast.socket_client] [Public Broadcast(192.168.1.31):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 8009)), retrying in 5.0s
2022-06-05 03:39:28 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error reading from socket.
2022-06-05 03:39:28 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Error communicating with socket, resetting connection
2022-06-05 03:39:28 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.38):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 32104)), retrying in 5.0s
2022-06-05 03:39:53 WARNING (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Heartbeat timeout, resetting connection
2022-06-05 03:40:09 ERROR (Thread-8) [pychromecast.socket_client] [Kitchen Assistant(192.168.1.38):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.38', 8009)), retrying in 5.0s
2022-06-05 03:40:14 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error reading from socket.
2022-06-05 03:40:14 WARNING (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Error communicating with socket, resetting connection
2022-06-05 03:40:15 ERROR (Thread-9) [pychromecast.socket_client] [First Floor(192.168.1.31):32104] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.31', 32104)), retrying in 5.0s
2022-06-05 04:11:35 WARNING (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Heartbeat timeout, resetting connection
2022-06-05 04:11:38 ERROR (Thread-16) [pychromecast.socket_client] [Living Room Vizio(192.168.1.172):8009] Failed to connect to service ServiceInfo(type='mdns', data='Living Room Vizio._googlecast._tcp.local.'), retrying in 5.0s
2022-06-05 05:31:46 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices 7b0b4fe6b9c656f4c0e67ca65f5a26ca, c264b09466926376bfa7d2860feec206
2022-06-05 07:41:03 ERROR (MainThread) [homeassistant.components.steam_online] Error fetching steam_online data: Server took too long to respond
2022-06-05 08:58:16 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
